### ISSUE TITLE
request: results to build in results view

### ISSUE THREAD

**Issue by davy79** [amitab/atom-cscope#1]
First of all: Thank you for taking the initiative for cscope support!
I was really missing some of it's features when I switched to atom.

I realize it is still very young, but I only have 2 issues with it for the moment:
1. when I close the results pane, I have to "click" inside the editor to regain control (get a cursor back)
2. I don't want to use the mouse at all if possible and currently I have to click the result to go to the resulting file:line

would it be possible to pipe the results to the build in atom find results view?
That would solve all issue.

Unfortunately I know absolutely nothing about atom plugins

**Comment by amitab** [comment]
@davy79 Thanks for trying out this package!
I agree with what you said about not using the mouse if possible.
Unfortunately there isn't any atom find results view. But I can try to mimic those functionalities in the current results view. 
Just so that I have it right - 
1. you want to be able to navigate the results list using the arrow keys right?
2. Also when you said atom find results view, did you mean you want the results to show up in a new tab just like the one that shows up when you perform a search in project?

**Comment by davy79** [comment]
aha, I knew there must be a reason for not using the default "find results" tab
1. yes navigating by arrow keys is fine, "enter" to go to the highlighted result (same as "click" now)
2. no, the current results pane is very good, I like it! all info is there along with preview etc. no need for a different tab that you have to return to afterwards to close it... I'm just wondering why I seem to lose all focus when pressing "esc" or "ctrl-alt-o" to close the pane... then I don't have a cursor and actually have to click with the mouse inside the editor to regain focus to the editor window.
   Every indication is there that there should be active focus on the current editor pane (blue line in the tab, current line is highlighted) but there just isn't a cursor until the editor is clicked :-)

**Comment by amitab** [comment]
@davy79 Check out the new release!
Just give it a try and if you face any issue, open one here.

**Comment by davy79** [comment]
I'll try it right away!

**Comment by davy79** [comment]
OK, the focus issue is resolved. great!
And I can also navigate the search results by keyboard! 
Unfortunately I immediately ran into an error after a search for which I have opened another issue#2 with the details.
